"""The committed CLO answer key's authoring path — one place, two callers.

``tests/test_quality_harness.py`` asserts the committed
``answer_keys/cairn-clo-xvii-dac.json`` reproduces byte-for-byte from what this
module builds, and the key itself was generated by running it. Keeping the two
on one code path is what makes the regeneration assertion mean "the committed
key is what the documents say" rather than "the committed key equals itself".

Offline and deterministic end to end: committed text fixtures →
``collateral_schedule_parser`` → ``DealAnswerKey.from_trustee_liability_summaries``.
No engine module appears anywhere on it — see that constructor's docstring for
why that is the property this whole surface rests on.
"""

from __future__ import annotations

from pathlib import Path

from loanwhiz.primitives.collateral_schedule_parser import (
    ReportLiabilitySummary,
    parse_liability_summary_text,
)
from loanwhiz.primitives.reconciliation_answer_key import DealAnswerKey

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "collateral_schedule"

CLO_DEAL_ID = "cairn-clo-xvii"
CLO_DEAL_NAME = "Cairn CLO XVII DAC"

#: The three monthly trustee reports Euronext's listing carries for this issuer,
#: in reporting order. January 2025 is absent from the exchange's filing, so the
#: series is deliberately not contiguous and nothing is interpolated.
CLO_REPORT_FIXTURES: tuple[tuple[str, str], ...] = (
    ("cairn-clo-xvii-december-2024.txt", "December 2024"),
    ("cairn-clo-xvii-february-2025.txt", "February 2025"),
    ("cairn-clo-xvii-march-2025.txt", "March 2025"),
)


def clo_report_summaries() -> list[ReportLiabilitySummary]:
    """Parse every committed Cairn trustee report, strictly.

    ``strict=True`` is not a default being restated: it makes each summary pass
    the parser's own acceptance oracle — the per-class balances against the
    report's stated total, and the coverage tests against the report's *second*
    rendering of them in the opposite column order — before any of it reaches an
    answer key.
    """
    return [
        parse_liability_summary_text(
            (FIXTURE_DIR / filename).read_text(encoding="utf-8"),
            period_label=period_label,
            strict=True,
        )
        for filename, period_label in CLO_REPORT_FIXTURES
    ]


def clo_key_from_reports() -> DealAnswerKey:
    """The Cairn answer key, authored from those reports."""
    return DealAnswerKey.from_trustee_liability_summaries(
        clo_report_summaries(),
        deal_id=CLO_DEAL_ID,
        deal_name=CLO_DEAL_NAME,
    )
