"""The committed CLO answer key's authoring path — one place, two callers.

``tests/test_quality_harness.py`` asserts the committed
``answer_keys/cairn-clo-xvii-dac.json`` reproduces byte-for-byte from what this
module builds, and the key itself was generated by running it. Keeping the two
on one code path is what makes the regeneration assertion mean "the committed
key is what the documents say" rather than "the committed key equals itself".

**Two documents, two constructors, one key** (#495). Cairn publishes its
coverage-test results in monthly trustee reports and its two Priorities of
Payments in a quarterly Note Valuation Report, so each has its own builder here
and :func:`clo_key_from_all_documents` is the union that gets committed. The
per-document builders stay separate rather than being folded into the union:
each one's regressions assert what *that* document does and does not state, and
merging them would leave those assertions nothing to hold.

Offline and deterministic end to end: committed text fixtures →
``collateral_schedule_parser`` / ``note_valuation_parser`` → the matching
``DealAnswerKey`` constructor. No engine module appears anywhere on it — see
those constructors' docstrings for why that is the property this whole surface
rests on.
"""

from __future__ import annotations

from pathlib import Path

from loanwhiz.primitives.collateral_schedule_parser import (
    ReportLiabilitySummary,
    parse_liability_summary_text,
)
from loanwhiz.primitives.note_valuation_parser import parse_note_valuation_text
from loanwhiz.primitives.notes_cash_parser import NotesCashReport
from loanwhiz.primitives.reconciliation_answer_key import (
    DealAnswerKey,
    merge_answer_keys,
)

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "collateral_schedule"
NOTE_VALUATION_FIXTURE_DIR = Path(__file__).parent / "fixtures" / "note_valuation"

CLO_DEAL_ID = "cairn-clo-xvii"
CLO_DEAL_NAME = "Cairn CLO XVII DAC"

#: The three monthly trustee reports Euronext's listing carries for this issuer,
#: in reporting order. January 2025 is absent from the exchange's filing, so the
#: series is deliberately not contiguous and nothing is interpolated.
CLO_REPORT_FIXTURES: tuple[tuple[str, str], ...] = (
    ("cairn-clo-xvii-december-2024.txt", "December 2024"),
    ("cairn-clo-xvii-february-2025.txt", "February 2025"),
    ("cairn-clo-xvii-march-2025.txt", "March 2025"),
)

#: The Note Valuation Reports Euronext's listing carries — one, as-of 08/01/2025.
#: Its period is January 2025, which is precisely the month the trustee-report
#: series is missing, so the two document sets cover disjoint dates.
CLO_NOTE_VALUATION_FIXTURES: tuple[tuple[str, str], ...] = (
    ("cairn-clo-xvii-january-2025.txt", "January 2025"),
)


def clo_report_summaries() -> list[ReportLiabilitySummary]:
    """Parse every committed Cairn trustee report, strictly.

    ``strict=True`` is not a default being restated: it makes each summary pass
    the parser's own acceptance oracle — the per-class balances against the
    report's stated total, and the coverage tests against the report's *second*
    rendering of them in the opposite column order — before any of it reaches an
    answer key.
    """
    return [
        parse_liability_summary_text(
            (FIXTURE_DIR / filename).read_text(encoding="utf-8"),
            period_label=period_label,
            strict=True,
        )
        for filename, period_label in CLO_REPORT_FIXTURES
    ]


def clo_key_from_reports() -> DealAnswerKey:
    """The Cairn answer key, authored from those reports."""
    return DealAnswerKey.from_trustee_liability_summaries(
        clo_report_summaries(),
        deal_id=CLO_DEAL_ID,
        deal_name=CLO_DEAL_NAME,
    )


def clo_note_valuation_report() -> NotesCashReport:
    """Parse every committed Cairn Note Valuation Report, strictly.

    ``strict`` is the default and is spelled out for the same reason it is on
    the trustee side: it is what makes each period pass ``note_valuation_parser``'s
    own acceptance oracle — every waterfall's step sum against the report's
    stated available funds, its printed running balance chained without a break,
    the Distribution Summary against its own totals row, and each class's applied
    rate against the Executive Summary's separate printing of it — before any of
    it reaches an answer key.
    """
    return NotesCashReport(
        deal_name=CLO_DEAL_NAME,
        periods=[
            parse_note_valuation_text(
                (NOTE_VALUATION_FIXTURE_DIR / filename).read_text(encoding="utf-8"),
                period_label=period_label,
                strict=True,
            )
            for filename, period_label in CLO_NOTE_VALUATION_FIXTURES
        ],
    )


def clo_key_from_note_valuation() -> DealAnswerKey:
    """The Cairn answer key's PoP half, authored from the Note Valuation Report."""
    return DealAnswerKey.from_note_valuation_report(
        clo_note_valuation_report(),
        deal_id=CLO_DEAL_ID,
        deal_name=CLO_DEAL_NAME,
    )


def clo_key_from_all_documents() -> DealAnswerKey:
    """The committed Cairn answer key — everything this deal publishes.

    The union of both routes, and what ``answer_keys/cairn-clo-xvii-dac.json``
    is regenerated from. The two documents' periods are disjoint by date, which
    is a fact about Euronext's filings rather than a choice: the exchange carries
    no January trustee report and no December/February/March Note Valuation
    Report. ``merge_answer_keys`` refuses a collision rather than reconciling
    one, so if a later filing overlaps, this fails loudly instead of quietly
    preferring one document's figures.
    """
    return merge_answer_keys(clo_key_from_reports(), clo_key_from_note_valuation())
