"""What a loan tape *is*, as distinct from what it says.

A loan-level tape can reach LoanWhiz two ways, and they are not interchangeable:

- **Filed** under Article 7(1)(a) of the Securitisation Regulation — the
  originator/sponsor/SSPE's own disclosure, in the ESMA RTS annex template, with
  the field codes and the vocabularies the template mandates.
- **Derived** from an investor or trustee report — reconstructed by LoanWhiz
  from a document published for a different purpose, resolved onto the same
  canonical columns so downstream analytics work, but *not* a regulatory filing
  and not stated in the RTS's coded vocabularies.
- **Synthetic** — generated by LoanWhiz. The file is published and reads like
  any other tape, but no row describes a real obligor, so nothing computed from
  it is evidence about a real pool.

The two are indistinguishable once the numbers are in a DataFrame, and that is
exactly the problem. A derived tape presented as a filed one is **provenance
laundering**: every consumer downstream — a coverage ratio, a concentration
test, a governance view citing field codes — inherits an authority the data
never had. So the distinction is carried as a *required* value on the tape
itself rather than as prose in a docstring somebody may not read.

The same laundering has a second form, and it is the one that shipped: a
synthetic tape whose only declaration of being synthetic is the word in its
filename. A filename is not read by the evidence pack, the capability matrix or
the citation excerpt, so such a tape reported the ingestion channel of a filed
regulatory one. :class:`TapeScheme` closes that by moving the claim into the
identifier every one of those surfaces already holds.

Why a source *kind* and not a deal flag
---------------------------------------
"Derived from an investor/trustee report" is a property of the **channel**, not
of any one deal. European and US CLOs are typically private transactions for
Securitisation-Regulation purposes and list on exchange-regulated markets, so
their asset-level reports go to Competent Authorities, Noteholders and
prospective investors rather than to a securitisation repository. Any deal in
that position is reachable only through the derived channel. The enum below
therefore names channels; nothing here names an issuer.

What this module does **not** do
--------------------------------
It defines no second provenance record. Per-field provenance already has a home
in :mod:`loanwhiz.domain.provenance` — :class:`FieldProvenance` keyed into a
:data:`ProvenanceMap`, whose ``citation.page_or_row`` is where a regulatory
locator belongs and whose ``citation`` may carry **no** locator at all. A tape
mapper populates that map; it does not invent a parallel one.

Import note
-----------
``loanwhiz.domain``'s package ``__init__`` participates in an import cycle with
``loanwhiz.primitives``. Import a ``loanwhiz.primitives`` module before this one,
as :mod:`loanwhiz.domain.esma_annex_registry`'s existing callers already do.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field

from loanwhiz.domain.esma_annex_registry import AnnexSpec

__all__ = [
    "TapeChannel",
    "TapeScheme",
    "TapeSourceKind",
    "channel_for",
    "kind_for_scheme",
    "scheme_for",
    "source_kind_for",
    "underlying_url",
    "Correspondence",
    "AbsentColumn",
    "ApproximateCorrespondenceError",
    "locator_for_correspondence",
]


# ---------------------------------------------------------------------------
# The channel a tape arrived through
# ---------------------------------------------------------------------------


class TapeChannel(str, Enum):
    """How a tape's rows physically reached the DataFrame.

    Surfaced as ``EsmaTapeOutput.data_source``. This is a **narrower** question
    than :class:`TapeSourceKind` — two tapes can arrive down the same channel
    and be very different things — but it is the one every governance surface
    already renders, so it must never flatten the distinction that matters.

    There is no default member, and no code decides a channel by observing
    which loader branch ran. A channel is read off the tape's *kind*, which is
    read off its *identifier* (:func:`channel_for`), so the pairing below is
    the only place a channel is chosen.
    """

    #: Read straight from a published file (HuggingFace CSV/parquet, ``file://``).
    DIRECT = "direct"

    #: No published file exists; the rows were reconstructed at ingest from a
    #: source document the deal registers.
    DERIVED = "derived"

    #: Read from a published file whose rows LoanWhiz generated. The file is
    #: real; the obligors are not.
    SYNTHETIC = "synthetic"


class TapeSourceKind(str, Enum):
    """How a loan tape reached LoanWhiz — a closed vocabulary.

    There is deliberately **no default member**. A tape's kind is a fact about
    where it came from, and a default would let the most consequential claim in
    the system be made by omission.
    """

    #: Disclosed by the originator/sponsor/SSPE under Securitisation Regulation
    #: Art. 7(1)(a), in the ESMA RTS annex template.
    FILED_ARTICLE_7_1_A = "filed_article_7_1_a"

    #: Reconstructed by LoanWhiz from an investor or trustee report. Resolved
    #: onto canonical annex columns for analysis; **not** a regulatory filing.
    DERIVED_FROM_INVESTOR_REPORT = "derived_from_investor_report"

    #: Generated by LoanWhiz. The file is published and readable like any
    #: other, and every column may be well-formed — but no row describes a real
    #: obligor, property or loan, so no figure computed from it is evidence
    #: about a real pool. Filed and derived tapes both describe real assets and
    #: differ on *who stated them*; this one differs on whether the assets
    #: exist, which is why it cannot be a shade of either.
    SYNTHETIC_GENERATED = "synthetic_generated"

    @property
    def is_regulatory_filing(self) -> bool:
        """Whether a tape of this kind *is* a regulatory disclosure.

        The single predicate every provenance surface should branch on, so no
        surface has to re-derive the distinction from a label string.
        """
        return _FACTS[self].is_regulatory_filing

    @property
    def rts_coded_values(self) -> bool:
        """Whether values are stated in the RTS's own coded vocabularies.

        A filed tape carries RTS codes (``DFLT``, ``SNDB``, a NACE code). A
        derived tape carries the *source document's* words, because translating
        them into RTS codes would be a second mapping with no source behind it.
        Consumers comparing against an RTS code must check this first.
        """
        return _FACTS[self].rts_coded_values

    @property
    def describes_real_assets(self) -> bool:
        """Whether the rows describe assets that exist.

        The predicate a surface branches on before treating pool figures as
        evidence about the world. ``is_regulatory_filing`` answers a different
        question — who stated the data — and a derived tape answers ``False``
        there while still describing real loans.
        """
        return _FACTS[self].describes_real_assets

    @property
    def first_hand(self) -> bool:
        """Whether this tape is a **first-hand** account of the pool.

        The predicate a surface branches on when it must choose *between* a
        deal's sources rather than judge one on its own. A filed tape is the
        originator's own loan-level statement: nothing published stands closer
        to the pool. A derived tape is LoanWhiz's rendering of a document the
        deal already publishes — the document outranks the rendering of it. A
        synthetic tape is nobody's account of anything real.

        Distinct from both its neighbours, and the distinction is the whole
        point: ``describes_real_assets`` asks whether the rows describe assets
        that exist (a derived tape answers ``True``), ``is_regulatory_filing``
        asks who stated the data. Neither separates *the document* from *our
        reading of the document*, which is the only question a source-precedence
        rule is asking.
        """
        return _FACTS[self].first_hand

    @property
    def channel(self) -> TapeChannel:
        """The ingestion channel a tape of this kind is reported under.

        Pairing the channel to the kind here — rather than at the loader — is
        what makes it impossible for a synthetic tape to be reported as
        ``direct``: the loader has no branch that assigns a channel, it only
        reads this.
        """
        return _FACTS[self].channel

    @property
    def disclosure(self) -> str:
        """One sentence stating what this tape is, for any operator-facing surface.

        Written to be quoted verbatim. A surface that renders a tape's origin
        should render this rather than compose its own wording, so the claim
        cannot drift between views.
        """
        return _FACTS[self].disclosure


class _SourceKindFacts(BaseModel):
    """The facts each :class:`TapeSourceKind` member carries."""

    model_config = {"frozen": True}

    is_regulatory_filing: bool
    rts_coded_values: bool
    describes_real_assets: bool
    first_hand: bool
    channel: TapeChannel
    disclosure: str = Field(min_length=40)


#: Facts per member. Guarded for **total** coverage at import (below): a
#: registration-style table that silently misses a member would make a newly
#: added kind well-formed by accident, which is how a closed enum stops being
#: closed. There is no ``.get(..., default)`` anywhere in this module.
_FACTS: dict[TapeSourceKind, _SourceKindFacts] = {
    TapeSourceKind.FILED_ARTICLE_7_1_A: _SourceKindFacts(
        is_regulatory_filing=True,
        rts_coded_values=True,
        describes_real_assets=True,
        first_hand=True,
        channel=TapeChannel.DIRECT,
        disclosure=(
            "Filed by the originator, sponsor or SSPE under Article 7(1)(a) of "
            "the Securitisation Regulation, in the ESMA RTS annex template."
        ),
    ),
    TapeSourceKind.DERIVED_FROM_INVESTOR_REPORT: _SourceKindFacts(
        is_regulatory_filing=False,
        rts_coded_values=False,
        describes_real_assets=True,
        first_hand=False,
        channel=TapeChannel.DERIVED,
        disclosure=(
            "Derived by LoanWhiz from an investor/trustee report; NOT filed "
            "under Article 7(1)(a) and not a regulatory disclosure. Values are "
            "the source document's own, not ESMA RTS codes."
        ),
    ),
    TapeSourceKind.SYNTHETIC_GENERATED: _SourceKindFacts(
        is_regulatory_filing=False,
        rts_coded_values=False,
        describes_real_assets=False,
        first_hand=False,
        channel=TapeChannel.SYNTHETIC,
        disclosure=(
            "Generated by LoanWhiz. NOT filed under Article 7(1)(a), not a "
            "regulatory disclosure, and not observed data: no row describes a "
            "real obligor, property or loan, so no figure computed from this "
            "tape is evidence about a real pool."
        ),
    ),
}

_missing = sorted(kind.value for kind in TapeSourceKind if kind not in _FACTS)
if _missing:  # pragma: no cover - import-time guard, asserted by test
    raise RuntimeError(
        f"TapeSourceKind members {_missing} carry no facts. Every member must "
        "declare is_regulatory_filing / rts_coded_values / disclosure: a member "
        "with no entry would answer the derived-vs-filed question by accident."
    )
del _missing


# ---------------------------------------------------------------------------
# The identifier that declares what a tape is
# ---------------------------------------------------------------------------


class TapeScheme(str, Enum):
    """URI schemes that state a tape's provenance in the identifier itself.

    A tape is passed between surfaces as a bare string — a registry entry, a
    cache key, a citation's ``document``. Anything not carried by that string
    has to be carried by a parameter somebody can forget to pass, which is how
    a synthetic tape came to report ``direct``. So the scheme prefix *is* the
    declaration, and every surface holding the string can recover it.

    Closed, with no default member, for the reason :class:`TapeSourceKind` has
    none: this decides the most consequential claim the system makes about a
    tape, and a default would let it be made by omission.

    Adding a synthetic dataset — in any asset class — needs no code change:
    register its URL with the ``synthetic:`` prefix.
    """

    #: Reconstructed from the collateral schedule of a monthly trustee report.
    #: The remainder names the source document, not a tape file.
    TRUSTEE_REPORT = "derived+trustee-report"

    #: Generated by LoanWhiz. The remainder is an ordinary published tape file
    #: and is read exactly like any other; the scheme states that its rows
    #: describe nobody.
    SYNTHETIC = "synthetic"


#: Scheme → what a tape carrying it **is**. Guarded for total coverage below,
#: like :data:`_FACTS`: a scheme with no kind would answer the question by
#: falling off the end of a lookup. There is no ``.get(..., default)`` here.
_SCHEME_KINDS: dict[TapeScheme, TapeSourceKind] = {
    TapeScheme.TRUSTEE_REPORT: TapeSourceKind.DERIVED_FROM_INVESTOR_REPORT,
    TapeScheme.SYNTHETIC: TapeSourceKind.SYNTHETIC_GENERATED,
}

_missing_schemes = sorted(s.value for s in TapeScheme if s not in _SCHEME_KINDS)
if _missing_schemes:  # pragma: no cover - import-time guard, asserted by test
    raise RuntimeError(
        f"TapeScheme members {_missing_schemes} declare no source kind. A "
        "scheme with no kind would make the most consequential claim about a "
        "tape by omission."
    )
del _missing_schemes


def kind_for_scheme(scheme: TapeScheme) -> TapeSourceKind:
    """What a tape carrying *scheme* is. Total — every member has an entry."""
    return _SCHEME_KINDS[scheme]


def scheme_for(url: str) -> TapeScheme | None:
    """The provenance scheme *url* declares, or ``None`` for a plain URL."""
    for scheme in TapeScheme:
        if url.startswith(f"{scheme.value}:"):
            return scheme
    return None


def source_kind_for(url: str) -> TapeSourceKind | None:
    """What the tape at *url* **is**, decided by its identifier alone.

    Returns ``None`` for an ordinary published tape URL. ``None`` means *the
    source kind is not declared* — deliberately **not**
    :attr:`TapeSourceKind.FILED_ARTICLE_7_1_A`. LoanWhiz's other tapes are read
    from published files with no evidence in this repo about whether those
    files are the originator's Article 7(1)(a) disclosure or a redistribution
    of it, and inventing that claim as a default is precisely the fabrication
    this module exists to prevent. A surface rendering provenance must handle
    three answers, not two.
    """
    scheme = scheme_for(url)
    return None if scheme is None else _SCHEME_KINDS[scheme]


def underlying_url(url: str) -> str:
    """*url* with any provenance scheme stripped — what the string names.

    For a ``synthetic:`` tape that is the published file to read. For a derived
    URI it is the source document, and the deriver (not a file reader) consumes
    it. A plain URL is returned unchanged, so this is safe to call on anything.
    """
    scheme = scheme_for(url)
    return url if scheme is None else url[len(scheme.value) + 1 :]


def channel_for(url: str) -> TapeChannel:
    """The ingestion channel the tape at *url* is reported under.

    The single decision point for ``data_source``, and the reason a synthetic
    tape cannot be reported as ``direct``: the channel is read off the kind,
    the kind off the identifier, and no loader branch assigns one. An
    undeclared identifier is :attr:`TapeChannel.DIRECT` — it names a published
    file read straight from its URL, which is what ``direct`` has always meant.
    That is a statement about the *channel* only; it asserts nothing about what
    the tape is, which is why :func:`source_kind_for` still answers ``None``.
    """
    kind = source_kind_for(url)
    return TapeChannel.DIRECT if kind is None else kind.channel


# ---------------------------------------------------------------------------
# How closely a source column corresponds to an annex field
# ---------------------------------------------------------------------------


class Correspondence(str, Enum):
    """How a source column relates to the annex field it resolves onto."""

    #: The source column *is* the annex field's datum. A regulatory locator is
    #: genuine and must be emitted.
    EXACT = "exact"

    #: The source column is near the annex field but not the same datum — a
    #: different classification scheme, a different geography, a different unit.
    #: It must resolve onto a **code-less** column, so no locator can be built.
    APPROXIMATE = "approximate"


class ApproximateCorrespondenceError(ValueError):
    """Raised when a declared correspondence contradicts the annex table.

    Both directions are errors, and the second is the one that ships (#453):

    - ``APPROXIMATE`` onto a column the annex *does* code — the laundering this
      module exists to prevent, caught before a fabricated locator can be built.
    - ``EXACT`` onto a column the annex does *not* code — a silently
      locator-less field that reads as a deliberate absence but is really a
      missing table row.
    """


def locator_for_correspondence(
    spec: AnnexSpec,
    canonical_column: str,
    correspondence: Correspondence,
) -> str | None:
    """Return the regulatory locator a mapping row is entitled to.

    This is the single decision point for "does this value get a field code?".
    It refuses rather than resolving by convention, so an approximate mapping
    onto a regulatory code is not a thing anyone can write and have work.

    Args:
        spec: The annex the tape resolves through.
        canonical_column: The canonical column the source field maps onto.
        correspondence: What the mapping author is claiming about the fit.

    Returns:
        The ``"<code> · <description>"`` locator for an ``EXACT`` mapping, or
        ``None`` for an ``APPROXIMATE`` one — provenance visibly absent.

    Raises:
        ApproximateCorrespondenceError: when the claim and the annex table
            disagree in either direction.
        KeyError: when *canonical_column* is not in this annex's table at all.
    """
    record = spec.field_for_column(canonical_column)
    if record is None:
        raise KeyError(
            f"{spec.annex_id}: no field resolves column {canonical_column!r}. "
            "Add a row to the annex table (an extension field with code=None if "
            "the RTS defines none) rather than mapping onto a column it lacks."
        )

    if correspondence is Correspondence.EXACT:
        if record.code is None:
            raise ApproximateCorrespondenceError(
                f"{spec.annex_id}: column {canonical_column!r} is an extension "
                "field with no RTS code, so an EXACT correspondence cannot yield "
                "a locator. Either the annex table is missing the real field, or "
                "this mapping is APPROXIMATE and should say so."
            )
        return spec.locator_for(record.field_name)

    if record.code is not None:
        raise ApproximateCorrespondenceError(
            f"{spec.annex_id}: column {canonical_column!r} carries RTS code "
            f"{record.code!r}, so an APPROXIMATE mapping onto it would attach a "
            "regulatory locator to a value that is not that field's datum. Map "
            "it onto a code-less extension column instead."
        )
    return None


# ---------------------------------------------------------------------------
# Columns a source cannot supply
# ---------------------------------------------------------------------------


class AbsentColumn(BaseModel):
    """A canonical column the annex defines and this source does not supply.

    Absence is a *fact worth stating*, not an empty slot. The failure this
    record exists to prevent is the one #451 found in this very annex: Annex 4
    carries no default flag (default is an ``account_status`` value), so a
    corporate tape whose obligors are defaulted reported ``default_pct: 0.0`` —
    a silent zero indistinguishable from a clean pool.

    A mapper therefore emits **no key at all** for these columns, and declares
    them here so a consumer can tell "the source does not publish this" from
    "the source publishes this and it is zero".
    """

    model_config = {"frozen": True}

    canonical_column: str = Field(min_length=1)
    rts_code: str | None = Field(
        default=None,
        description="The RTS field code this column would carry, when it has one.",
    )
    reason: str = Field(
        min_length=20,
        description=(
            "Why this source cannot supply the column. An assertion about the "
            "world: say only what the source encodes, never that the datum does "
            "not exist."
        ),
    )
